app:
  name: video_platform_backend
  port: :8080

database:
  host: localhost
  port: :3306
  user: root
  password: 164621355
  name: video_platform_db
  MaxIdleConns: 10
  MaxOpenConns: 120

jwt:
  secret: my_secret_key
  expire_duration: 72

minio:
  endpoint: localhost:9000
  access_key: minioadmin
  secret_key: minioadmin
  use_ssl: false
  bucket: videos
